sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9a5cf61ad990_key -iv $encrypted_9a5cf61ad990_iv -in complex-k8s-273319-1d618e8cf9ae.json.enc -out complex-k8s-273319-1d618e8cf9ae.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file complex-k8s-273319-1d618e8cf9ae.json
  - gcloud config set project complex-k8s-273319
  - gcloud config set compute/zone us-west2-b
  - gcloud container clusters get-credentials complexk8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sinusekhar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sinusekhar/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
