sudo: required
services:
    - docker

before_install:
  - docker build -t sinusekhar/multidocker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sinusekhar/multidocker npm run test

after_success:
  - docker build -t sinusekhar/multi-client ./client
  - docker build -t sinusekhar/multi-nginx ./nginx
  - docker build -t sinusekhar/multi-server ./server
  - docker build -t sinusekhar/multi-worker ./worker
#Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push to Docker hub
  - docker push sinusekhar/multi-client
  - docker push sinusekhar/multi-nginx
  - docker push sinusekhar/multi-server
  - docker push sinusekhar/multi-worker



deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-518225494279"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
